
services:
#  practice-doc:
#    build: .
#    depends_on:
#      - mongodb
#    ports:
#      - 9080:9080 
#    networks:
#      - my-mongo-demo

  mongodb:
#    container_name: training-mongodb
    image: mongo:7
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_user
      - MONGO_INITDB_ROOT_PASSWORD=admin_pwd
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb:/data/db
      - mongodb:/data/config
    networks:
      - my-mongo-demo
networks:
  my-mongo-demo:
    driver: bridge
volumes:
  mongodb:
  mongoconfig: